version: '3'

services:
  nginx:
      image: nginx:1.13
      ports:
        - "80:80"
      volumes:
        - ./nginx/conf:/etc/nginx/conf.d
      depends_on:
        - python

  db:
      image: mysql:8.0
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: fastbooking
        MYSQL_USER: fastbook
        MYSQL_PASSWORD: gWqzP0up6FYm3P2cUfQRWmkM
      volumes:
        - ./mysql:/var/lib/mysql
        - ./sql:/docker-entrypoint-initdb.d

  python:
      build: ./python
      volumes:
        - ./python:/usr/src/app
      ports:
        - "8000:8000"
      depends_on:
        - db